### ISSUE TITLE
'NoneType' object has no attribute 'layers'

### ISSUE THREAD

**Issue by gorjious** [eweracs/HTLSManager#2]
Been getting this crash too when trying to open the HTLS Manager on an existing file.
<img width="748" alt="Screenshot 2022-07-28 at 09 02 36" src="https://user-images.githubusercontent.com/23149420/181424588-ea10ccea-3ed1-4a0b-9d8d-b4e30da7e32a.png">

**Comment by eweracs** [comment]
Ah. That means you opened it on a file with a very limited character set? I assume this crash happens when the default glyphs (naïvely set to o and n) don't appear in the font. Will post a fix soon. Thank you!

**Comment by eweracs** [comment]
Apologies, with "very limited" I meant a character set without the default glyphs "n" and "o" used by the plugin. Is it obvious yet I almost only do Latin fonts? ;)

Anyway, this is fixed in [13aa889](https://github.com/eweracs/HTLSManager/commit/13aa88990e4466542da388c0f4c9c4ad3a8ebcb4)

I should mention this is somewhat of a dirty fix, as opening the plugin on a font without any glyph will still crah. A substantial re-write will be necessary to accommodate for this rather edge-y case.

**Comment by gorjious** [comment]
Haha, no worries. I hope I'll bring a non-Latin, or at least, an Armenian perspective to the plugin. 

Interesting that you say that because the error wasn't popping up when opening a new glyphs file.
