### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by laepage** [eweracs/HTLSManager#4]
I’ve been able to run only one time HTLSManager on the file I’m working. All other times it crashed Glyphs. In other cases, for example when I tested the plugin with .glyphs files made from imported .otf-s, it just works. A recent crash report:

Traceback (most recent call last):

File “GlyphsApp/GlyphsApp/init.py”, line 1373, in callback_

File “plugin.py”, line 1343, in close_window

self.w.close()

File “vanillaWindows.py”, line 291, in close

if self._window.isSheet():

AttributeError: ‘NoneType’ object has no attribute ‘isSheet’

App:3.1-3133 Plugin:0.1-1

**Comment by eweracs** [comment]
Hi, thanks for the report. This is an issue related to something I still need to figure out – the last little fix I published yesterday addresses this, please re-install the plugin and it should work.

Note that switching between fonts and closing the currently open font won't work with the plugin, but otherwise, it should work.
