### ISSUE TITLE
Too tight "OO" vs "oo"

### ISSUE THREAD

**Issue by usted** [eweracs/HTLSManager#7]
Hi there

Thanks for a great tool!

I don't know if this is the right place to ask this, cause I use the HTLSManager. But maybe this is an HT Letterspacer issue? So I've ask it here as well: https://github.com/huertatipografica/HTLetterspacer/issues/71

I have found that the spacing of the uppercase "O" is almost identical to the lowercase "o", no matter what parameters I use. And therefore looks a bit too tight. It is suppose to be a bit larger, around 1.2x. Is that something you have experienced before and do you have a solution for it?

<img width="433" alt="Screenshot 2023-07-29 at 17 13 37" src="https://github.com/eweracs/HTLSManager/assets/5296382/401bde2b-661f-462b-9986-37f10cb85031">

My parameters are: paramArea:330 and paramDepth: 15

Thanks,
Andreas

**Comment by eweracs** [comment]
Hi, thanks for your question! The spacing is correct in terms of mathematics, but you will find that oo and OO generally need positive kerning. As you can see in your screenshot, oo is much tighter than nn, this is only natural. Same goes for OO.

So I would advise you to adjust this with kerning, since HHOHH and nnonn look completely fine.

**Comment by usted** [comment]
Thanks for the quick reply :)
